[0m22:06:30.894875 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BD0452FB90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BD0452D190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BD04154320>]}


============================== 22:06:30.900892 | d950f11b-1c0c-4cb4-964a-470b85dee7fa ==============================
[0m22:06:30.900892 [info ] [MainThread]: Running with dbt=1.8.4
[0m22:06:30.901875 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\kryvi\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init my_proj', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:06:30.920472 [debug] [MainThread]: Starter project path: D:\final_dbt_test\final_dbt_test\venv\Lib\site-packages\dbt\include\starter_project
[0m22:06:30.939471 [info ] [MainThread]: 
Your new dbt project "my_proj" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:06:30.942179 [info ] [MainThread]: Setting up your profile.
[0m22:06:30.944487 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m22:06:30.946389 [debug] [MainThread]: Command `dbt init` failed at 22:06:30.946389 after 0.16 seconds
[0m22:06:30.946389 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BD04154320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BD04ED5F70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BD04EC60C0>]}
[0m22:06:30.947393 [debug] [MainThread]: Flushing usage events
